# Generated by Django 3.2.18 on 2023-04-30 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=360, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id_article', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(null=True)),
                ('publish_time', models.CharField(blank=True, max_length=15, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('studylink', models.URLField(blank=True, max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('email', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('name', models.CharField(max_length=600, unique=True)),
                ('id_journal', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyType_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.articles')),
                ('studytype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.studytype')),
            ],
        ),
        migrations.CreateModel(
            name='Sous_Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.theme')),
            ],
        ),
        migrations.CreateModel(
            name='Author_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.articles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.authors')),
            ],
        ),
        migrations.CreateModel(
            name='Author_Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.affiliation')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.authors')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.journal'),
        ),
        migrations.CreateModel(
            name='Article_Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.articles')),
                ('sous_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.sous_theme')),
            ],
        ),
    ]
