# Generated by Django 4.1.7 on 2023-04-24 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli_covid19', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli_covid19.journal'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='studylink',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
