# Generated by Django 4.1.7 on 2023-04-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli_covid19', '0002_alter_articles_abstract_alter_articles_journal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
